### PR TITLE
Use `{processx::run}` to capture `cargo` output

### LINKED ISSUE #115: [Feature Proposal]: Produce better errors when `cargo` fails at runtime
## Before you read
This is an invitation to discussion. There is no need to implement this feature, but I do believe the end users of {extendr} could benefit from something like this.
## Problem outline
We run `cargo` in two scenarios: when a user uses public API like `rust_function` and when {knitr} is processing markdown.
https://github.com/extendr/rextendr/blob/00ce4650ee044e4b7c66ebeaecaa65c6d5ec7024/R/source.R#L281-L297
As you can see, right now we simply use `system2` with some `stderr`/`stdout` redirection and check its exit status.
If not zero, we throw a super-useful error with absolutely **no** details.

In a user session, when R has access to `stdout` and `stderr`, `cargo` displays its output in the console (unless `quiet = TRUE`).
This helps to resolve any compilation errors.
What happens if no `stdout`/`stderr` is available or if `quiet = TRUE`? Well, nothing is printed and the only useful information is the error message saying `"Compilation failed. Aborting"`. This is especially painful when running `R CMD check` or `rcmdcheck::rcmdcheck`, as it shows you errors but not `stdout`/`stderr`. 

## Proposed solution
As suggested by dfalbel in Discord discussion, we use `rlang::abort()` to produce an `rlang::rlang_error` when calling `rextendr::ui_throw()`.
`rlang::abort()` [allows](https://rlang.r-lib.org/reference/abort.html) attaching additional named data to the thrown error using its `...` argument. 
So, we could augment the invocation of `cargo`, capture its errors and attach them to our `rextendr::rextendr_error`. 
This way, even if we disable verbose output for `cargo`, we will be able to provide an explanation to the user of what went wrong.
Sounds simple? Well, not really, here are the details.

### Capturing `cargo` output
The desired solution is to be able to **both** *display* and *capture* output of `cargo`, preserving its color scheme and formatting. We would also want to be able to 'switch off' verbose output yet still capture it for the purpose of error formatting, satisfying `quiet = TRUE`.

`cargo` is a little bit tricky. It prints to `stdout` information like passed/failed tests, but sends all compilation info, warnings and errors to `stderr` (this includes all these fancy `'Updating crates.io`', `'Compiling x'`, `'Finished'`, etc messages).
In our scenario, we run `cargo build --lib`, so there should be no `stdout` at all, but for now let us assume there may be `stdout` during compilation. Just a reminder that we are discussing runtime compilation, where we create Rust crate ourselves, so I expect no `build.rs` or any other build tricks, just plain compilation of (likely one) Rust file(s).

- Problem: [`system2`](https://rdrr.io/r/base/system2.html) cannot simultaneously print and capture output to a variable or file.
- Solution: `cargo` is a separate executable, so let's run it properly: [`processx::run()`](https://rdrr.io/cran/processx/man/run.html). We depend on {processx} through {callr}, which is used for out-of-process wrapper generation. The `processx::run()` allows to both capture and print out `stdout` and `stderr`, separately. If configured correctly, it will behave as `system2()`, but the returned value will contain not only `$status` code, but also `$stdout` and `$stderr`. 
Using additional parameters like `echo` and `echo_cmd`, we can control all of the printed output.
Instead of passing around weird `stdout`/`stderr` variables with obscure values of `""`/`NULL`, we can have one parameter `quiet = logical(1)`, in line with other functions, and switch off all printed output based on the value of this flag.
- Changes: Remove `stdout` and `stderr` from `rextendr:::invoke_cargo()`, add a single `quiet` argument. Replace call to `system2()` with call to `processx::run()` or `callr::run()` (a re-exported function), adjust parameters, record `stderr` in a separate variable.
- Drawbacks:
  -  When capturing `stderr`, on Windows the `stdout`/`stderr` interleaving may break, likely caused by `stdout` buffering.  However, because `cargo` does not write to `stdout` that much in our scenarios, this problem is unobserved. *No remedy is available.*
  - When writing and capturing `stderr`, `processx::run()` prints child process' `stderr` to R's `stdout`. As a result, when using `{knitr}`, compilation information leaks to the captured output. 
  *Temporary fix*: execute {knitr} with `quiet = TRUE`. 
  *Permanent fix*: revise `rextendr::rust_eval()`, which compiles and runs code fragment in one go. Suggested solution: make `rust_eval_fun()` which compiles fragment and returns R wrapper function, which allows to separately capture compilation `stdout` and any `stdout` printed by Rust snippet. Can be implemented together with improving {rextendr} {knitr} engine.
  
- Problem: `cargo` stdout is unstructured. Multiple errors can be emitted alongside warnings. The same stream contains information about successful compilation, which should be excluded when capturing error messages.
- Solution: The output is pretty straightforward. It can be concatenated into a single string. We can match lines on `"\nwarning:|\nerror:"` or something similar. Using this pattern we can split the input into (multi-line) substrings and trim extra spaces from both sides. If matched correctly, then all strings starting with `"^error:"` will contain information about strictly one error. Same applies to `"^warning:"`. 
Collected `errors` and `warnings` can be sent along `rextendr::rextendr_error` as `cargo_errors = list(errors = errors, warnings = warnings)`.
- Drawbacks: 
  - Parsing generally unknown and unstructured output which may change in future versions of Rust. In the worst-case scenario, we won't get any useful information from `stderr`, which is what we have right now (so no regression). In the best-case scenario, we will capture each error and warning separately, ignoring all garbage about successful compilations. This postprocessing only happens when `cargo` fails, so there should be at least one error in the output. Even if we grab everything in the `stderr`, it is still better than what we have right now.
  - {cli} does not support advanced ansi-aware regex, so for now we first strip all of the output of ansi sequences and process plain text. 
  *Permanent fix*: Investigate how to utilize {cli} ansi-aware regex and possibly simplify expressions, which may allow us to include `cargo` error messages in our `rextendr::rextendr_error`, preserving **all** formatting, including colors.
  
### Printing `rextendr_error`
In general, {rlang} does not display additional fields and metadata when printed `rlang::rlang_error`-derived errors. What we would like is to have two display modes: a shorter form which prints only part of errors/warnings, which is used everywhere (especially when the error is uncaught), and a longer form which prints all of the `cargo` errors/warnings, which should be accessed using `summary` `S3` method. 

- Problem: To print `rextendr::rextendr_error` in short form, we need to be able to carefully wrap error messages and subset `n` lines from each error message, preserving format. Otherwise, we will lose useful information like where in the source code the error occurred. It is desirable to offload as much formatting as possible to {rlang} or any other base-type methods.
- Solution:  <s>We can achieve this by overloading two `S3` methods:</s> **This is blocked by** https://github.com/r-lib/rlang/issues/1205
  ```
  conditionMessage.rextendr_error <- function(c) {}
  format.rextendr_error <- function(x, ...) {}
  ```
  `conditionMessage` is invoked by {rlang} when formatting its body. This method provides the output of the base class plus additional information about `cargo` errors in short form. This implementation automatically propagates to other printing methods.
`format` is invoked when formatting, e.g., for `summary` method. We can use one of the {rlang} parameters to determine if the output should be simplified or detailed. When detailed, we output `cargo` errors in the long form. This automatically enables `summary()` to print detailed information.

- Drawbacks: 
  - <s>Due to {rlang}'s [implementation](https://github.com/r-lib/rlang/blob/c2510b8574e4429ccb9eefc805054a611e68f139/R/cnd-error.R) of formatting methods, calling `NextMethod()` in `format()` results in an infninte recursion. </s>
  <s>*Temporary fix*: In `rextendr::format.rextendr_error` temporarily strip error object of all `"rextendr_*"` classes and then dispatch `S3`, which will then resolve into correct {rlang} generics, avoiding infinite recursion. This, however, incorrectly prints the error type.</s>
  *Fix*: Limitations are avoided using options.
  - Wrapping and printing out error messages can be tricky. We want to preserve the structure and (possibly) theme.
    *Temporary fix*: we handle plain text only, wrap lines preserving original line breaks as well.
    *Permanent fix*: we use ansi-aware procedure to process original error messages, preserving full formatting.
    
## The best part: reproducible example:
https://github.com/Ilia-Kosenkov/rextendr/tree/callr-cargo
Successful CI checks of this branch https://github.com/Ilia-Kosenkov/rextendr/actions/runs/838499744
<details>
<summary>Before</summary>

``` r
# Catching error
err <- tryCatch(rextendr::rust_function("fn invalid syntax(){}", quiet = TRUE), error = identity)
# Short form
print(err)
#> <error/rextendr_error>
#> Rust code could not be compiled successfully. Aborting.
#> Backtrace:
#>  1. base::tryCatch(...)
#>  5. rextendr::rust_function("fn invalid syntax(){}", quiet = TRUE)
#>  6. rextendr::rust_source(code = code, env = env, ...)
#>  7. rextendr:::invoke_cargo(...)
#>  8. rextendr:::ui_throw("Rust code could not be compiled successfully. Aborting.")
# Long form
summary(err)
#> <error/rextendr_error>
#> Rust code could not be compiled successfully. Aborting.
#> Backtrace:
#>     x
#>  1. +-base::tryCatch(...)
#>  2. | \-base:::tryCatchList(expr, classes, parentenv, handlers)
#>  3. |   \-base:::tryCatchOne(expr, names, parentenv, handlers[[1L]])
#>  4. |     \-base:::doTryCatch(return(expr), name, parentenv, handler)
#>  5. \-rextendr::rust_function("fn invalid syntax(){}", quiet = TRUE)
#>  6.   \-rextendr::rust_source(code = code, env = env, ...)
#>  7.     \-rextendr:::invoke_cargo(...)
#>  8.       \-rextendr:::ui_throw("Rust code could not be compiled successfully. Aborting.")
```

<sup>Created on 2021-05-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

image

</details>

<details>
<summary>After</summary>

``` r
# Catching error
err <- tryCatch(rextendr::rust_function("fn invalid syntax(){}", quiet = TRUE), error = identity)
# Short form
print(err)
#> <error/rextendr_error>
#> 
#> x `cargo` emitted 3 errors:
#>   1. error: expected one of `(` or `<`, found `syntax`
#>      --> src\lib.rs:3:12
#>       |...
#>   2. error: aborting due to previous error
#>   3. error: could not compile `rextendr1`
#> Backtrace:
#>  1. base::tryCatch(...)
#>  5. rextendr::rust_function("fn invalid syntax(){}", quiet = TRUE)
#>  6. rextendr::rust_source(code = code, env = env, ...)
#>  7. rextendr:::invoke_cargo(...)
#>  8. rextendr:::ui_throw(...)
```

<sup>Created on 2021-05-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

</details>

### PR DESCRIPTION
**Pull request by Ilia-Kosenkov**
This is an attempt to fix #115. Currently, we get little to no information about the reason the compilation has failed.
Now we can throw an error that contains the output of `cargo` marking problematic code fragments.
``` r
rextendr::rust_function("fn wrong_function(x : i33) -> f33 { false }")
#> i build directory: 'C:/Users/[redacted]/AppData/Local/Temp/RtmpM11rtn/file2e184e2156d4'
#> Error: Rust code could not be compiled successfully. Aborting.
#> error[E0412]: cannot find type `i33` in this scope
#>  --> src\lib.rs:3:23
#>   |
#> 3 | fn wrong_function(x : i33) -> f33 { false }
#>   |                       ^^^ help: a builtin type with a similar name exists: `i32`
#> 
#> 
#> error[E0412]: cannot find type `f33` in this scope
#>  --> src\lib.rs:3:31
#>   |
#> 3 | fn wrong_function(x : i33) -> f33 { false }
#>   |                               ^^^ help: a builtin type with a similar name exists: `f32`
#> 
#> 
#> error: aborting due to 2 previous errors
```

<sup>Created on 2021-12-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Screenshot 2021-12-12 232131

### CODE REVIEW

**Comment by malcolmbarrett** [comment]
Excited about this one!

**Comment by Ilia-Kosenkov** [comment]
@yutannihilation, Windows builds seem to fail because of the missing `-lbcrypt`. Can you make a PR to fix this so I can then merge master and re-run CI?
https://github.com/extendr/extendr/issues/339

File: R/source.R [hunk 1]
```diff
@@ -282,22 +270,63 @@ invoke_cargo <- function(toolchain, specific_target, dir, profile,
...
-    ui_throw("Rust code could not be compiled successfully. Aborting.")
+
+  if (!isTRUE(compilation_result$status == 0)) {
+    errors <-
+      message_buffer %>%
+      purrr::map_chr(stringi::stri_trim) %>%
+      purrr::map(jsonlite::parse_json) %>%
+      purrr::keep(
+        ~.x$reason == "compiler-message" && .x$message$level == "error"
+      )
```
Comment (Ilia-Kosenkov) [inline R/source.R:317]: Here I rely on the fact that `cargo` output is configured to produce JSONs. Should we have an extra `tryCatch` to handle a situation when the output is garbage and can't be parsed as JSON?

**Comment by Ilia-Kosenkov** [comment]
Also, the devel version of R seems to produce weird knitr output, will research it later.
https://github.com/extendr/rextendr/runs/4499559708?check_suite_focus=true#step:11:182

**Comment by yutannihilation** [comment]
Here's the PR: https://github.com/extendr/extendr/issues/339

**Comment by Ilia-Kosenkov** [comment]
So I realized that if an error message is too long (by default it is `options(warning.length = 1000)`, and measured in regular characters, including various invisible ANSI style delimiters), the text gets truncated, and if truncation corrupts ANSI sequence, the terminal gets screwed up (similar to what is shown in the image at the beginning of this thread). The limit can be increased up to I think `8170`, which will be automatically done by `rlang::abort` in the future https://github.com/r-lib/rlang/pull/1214. Still, 8000 is not that much, so first of all I implemented an algorithm that cuts off compiler messages if they no longer fit in the output buffer. The attached image shows how it looks like with a limit of `1000` characters.

image

The second step is to locally override options to set `warning.length` to `8000` so we can display large error messages. This should be enough for the majority of cases, when code fragment has one to five (I guess) reported errors. Same fragment but with a limit of `8000`:

image

The first 'could not compile' error message actually comes from the output of compilation process, and can be silenced with `quiet = TRUE`. Everything else is an error that can be re-inspected with `rlang::last_error()` or `rlang::last_trace()`:

image

**Comment by Ilia-Kosenkov** [comment]
Added `x` to the beginning of each 'error' in the 'details' list.
image

**Comment by Ilia-Kosenkov** [comment]
The changes are significant, I'd like an honest review from as many contributors as possible.

File: tests/testthat/_snaps/unix/helper-functions.md [hunk 2]
```diff
@@ -0,0 +1,25 @@
+# `ui_throw()` called by `rust_function()` captures Rust compilation errors
+
+    Rust code could not be compiled successfully. Aborting.
+    x error[E0412]: cannot find type `i33` in this scope
+     --> src/lib.rs:3:19
```
Comment (clauswilke) [inline tests/testthat/_snaps/unix/helper-functions.md:5]: Are you sure you want to snapshot these error messages? Any time something minor changes in rustc's output this will break.

File: R/source.R [hunk 3]
```diff
@@ -282,22 +270,65 @@ invoke_cargo <- function(toolchain, specific_target, dir, profile,
...
+      if (!is.null(specific_target)) {
+        sprintf("--target=%s", specific_target)
+      } else {
+        NULL
+      },
+      sprintf("--manifest-path=%s", file.path(dir, "Cargo.toml")),
+      sprintf("--target-dir=%s", file.path(dir, "target")),
+      if (profile == "release") "--release" else NULL,
+      "--message-format=json-diagnostic-rendered-ansi",
+      ifelse(
```
Comment (clauswilke) [inline R/source.R:294]: Why `ifelse` instead of `if () ... else`? `ifelse` is normally used for vectorized data. Also, it's inconsistent with line 292.

**Review by clauswilke — COMMENTED** [review]
Overall looks good to me. A few minor comments.

File: tests/testthat/_snaps/unix/helper-functions.md (hunk 2 above)
Comment (Ilia-Kosenkov) [reply tests/testthat/_snaps/unix/helper-functions.md:5]: I understand the danger, yet I trust Rust developer team and believe they will not change the output of `cargo`/`rustc`. Even if they will (e.g., if something like Rust 2.0 is released), I see no problem in updating snapshots. After all, every time `{rlang}`, `{cli}`, `{knitr}`, or any other library that produces formatted output has something changed under the hood, we are forced to update the snapshots (as soon as we notice). This also draws our attention to potential changes that we overlook.

Comment (clauswilke) [reply tests/testthat/_snaps/unix/helper-functions.md:5]: Ok, sounds good.

File: R/source.R [hunk 4]
```diff
@@ -118,16 +118,6 @@ rust_source <- function(file, code = NULL,
   # to be used by `system2()` below
   if (!isTRUE(quiet)) {
     ui_i("build directory: {.file {dir}}")
-
-    # `""` sends `cargo` output to R's standard output.
-    # R console displays to the user informaion about compilation steps and
```
[the remark this answers is not in the document]
Comment (Ilia-Kosenkov) [reply R/source.R:123]: I think it was present in the original code fragment, but I deleted it.

File: R/source.R (hunk 3 above)
Comment (Ilia-Kosenkov) [reply R/source.R:294]: Fixed this and a few other arguments. I think `{glue}` works better here than `sprintf()`.

**Comment by clauswilke** [comment]
Any idea what happened with the last series of commits, where now we don't see line-by-line changes anymore for file `R/source.R`?

**Comment by Ilia-Kosenkov** [comment]
Ok, I screwed up line endings, will fix it tomorrow.

**Comment by Ilia-Kosenkov** [comment]
Also, I think we are now missing compilation warnings (like when you have unused variables or parameters). It is not critical, but I'd like to capture that information as well and display it to the user. It should not be difficult, as we already have all the output in JSON. We just need to filter warnings and print them using `{cli}`. I'd like to implement it in this PR.

**Comment by Ilia-Kosenkov** [comment]
So I fixed the issue with line endings, started displaying warnings emitted by cargo, and also fixed a small bug that displayed one line of output even if `quiet = TRUE` was set. Now any interactive compilation is completely silent when `quiet = TRUE` is provided.

**Comment by Ilia-Kosenkov** [comment]
image

**Comment by yutannihilation** [comment]
Looks awesome! I'll try to find time to review this.

Just for information, processx is currently broken on UCRT R-devel on Windows. I'm suspecting the problem is something related to the difference between the OS's encoding (not necessarily UTF-8) and the R's native encoding (UTF-8), so rextendr might be affected. It is probably a bit too early to worry about this (and we don't have CI runner for this), but we might need to have better understanding about the encoding and the stdout/stderr of an external process.

https://cran.r-project.org/web/checks/check_results_processx.html

**Comment by Ilia-Kosenkov** [comment]
When we generate bindings out of process, we use `{callr}`, which AFAIK relies on `{processx}`, so we are already affected. https://github.com/r-lib/callr/blob/ea5c3df7788e43870a265b276d3a4ae103e91557/DESCRIPTION#L20

**Comment by yutannihilation** [comment]
Oh, I see. I think we should add an Windows runner with R-devel to our CI. It seems the UCRT is getting ready.

c.f. https://developer.r-project.org/Blog/public/2021/12/07/upcoming-changes-in-r-4.2-on-windows/index.html

I'll take a look on this.

**Comment by Ilia-Kosenkov** [comment]
Also it would be nice if you can migrate the second CI pipeline to r-actions instead of us doing all the heavy lifting, similar to R CMD check pipeline

File: R/source.R [hunk 5]
```diff
@@ -282,22 +269,117 @@ invoke_cargo <- function(toolchain, specific_target, dir, profile,
...
+        "--color=always"
+      } else {
+        "--color=never"
+      }
     ),
-    stdout = stdout,
-    stderr = stderr
+    echo_cmd = FALSE,
+    windows_verbatim_args = FALSE,
+    stderr = ifelse(isTRUE(quiet), "|", ""),
```
Comment (yutannihilation) [inline R/source.R:297]: You can also replace `ifelse()` with `if` here.

File: R/source.R [hunk 6]
```diff
@@ -282,22 +269,117 @@ invoke_cargo <- function(toolchain, specific_target, dir, profile,
...
+#' and throws errors if compilation was unsuccessful.
+#' @param compilation_result The output of `processx::run()`.
+#' @param message_buffer \[ character(n) \] Messages emitted by cargo to stdout.
+#' @param tty_has_colors \[ logical(1) \] Indicates if output
+#' supports ANSI sequences. If `FALSE`, ANSI sequences are stripped off.
+#' @param quiet Logical indicating whether compile output should be generated or not.
+#' @noRd
+check_cargo_output <- function(compilation_result, message_buffer, tty_has_colors, quiet) {
+  cargo_output <- message_buffer %>%
+    purrr::map_chr(stringi::stri_trim) %>%
```
Comment (yutannihilation) [inline R/source.R:353]: Maybe we can parse JSONs without trimming whitespaces? Just curious.

File: R/ui.R [hunk 7]
```diff
@@ -103,17 +103,66 @@ ui_w <- function(text = "", env = parent.frame()) {
...
+#' @param truncation_notification Message pattern appended if any `lines`
+#' were removed. Understands `cli` interpolation and
+#' `n_removed` integer variable, which is set to the number of removed lines.
+#' @return \[ ansi_character(n) \] A subset of `lines` with
+#' `truncation_notification` appended (if needed).
+#' @noRd
+subset_lines_to_fit_in_limit <- function(lines,
+                                         max_length = 1000,
+                                         truncation_notification = "{.val {n_removed}} compiler messages not shown.") {
+  n_removed <- 100L
```
Comment (yutannihilation) [inline R/ui.R:155]:
```suggestion
```

It looks this line is unnecessary.

File: R/ui.R [hunk 8]
```diff
@@ -103,17 +103,66 @@ ui_w <- function(text = "", env = parent.frame()) {
...
+  truncation_notification_size <- nchar(bullet_i(truncation_notification))
```
Comment (yutannihilation) [inline R/ui.R:156]: By default, `nchar()` measures the numbers of the characters, but it seems it's actually measured in bytes (see the last one is trancated by 334 repeats).

```
> cat("\u2705")
✅> 
> nchar("\u2705")
[1] 1
> nchar("\u2705", type = "width")
[1] 2
> nchar("\u2705", type = "byte")
[1] 3
> 
> withr::with_options(
+   list(warning.length = 1000),
+   warning(stringr::str_dup("\u2705", 333))
+ )
Warning message:
In force(code) :
  ✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅
> 
> withr::with_options(
+   list(warning.length = 1000),
+   warning(stringr::str_dup("\u2705", 334))
+ )
Warning message:
In force(code) :
  ✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅ [... truncated]
```

**Review by yutannihilation — COMMENTED** [review]
Generally looks good to me. Minor comments.

File: R/ui.R (hunk 7 above)
Comment (Ilia-Kosenkov) [reply R/ui.R:155]: This may be an overkill, but the trick here is to first compute the actual size of the message appended if lines are trimmed. This message is i) customizable ii) depends on the number of removed lines (which is unknown).
So I first assign an arbitrarily large value to `n_removed`, then I use `{cli}` to obtain the actual interpolated string and then use it to compute the length. Assuming we will never have more than 999 lines removed, it gives an upper limit on the length of the added string, which is enough to fit everything within the buffer.
If I remove this declaration, the `{cli}` will fail interpolation.

It is sort of a circular dependency -- `n_removed` depends on the length of the appended message, which in turn depends on `n_removed`.

File: R/ui.R (hunk 8 above)
Comment (Ilia-Kosenkov) [reply R/ui.R:156]: Interesting, the documentation on this topic is not as good as I expected, so I assumed we dealt with characters. I will use `type = "byte"`.

File: R/ui.R (hunk 7 above)
Comment (yutannihilation) [reply R/ui.R:159]: Ah, sorry, I just missed this variable is referenced by `truncation_notification`. Thanks for the explanation.

**Review by yutannihilation — APPROVED** [review]

**Comment by Ilia-Kosenkov** [comment]
I am getting a weird error https://github.com/extendr/rextendr/runs/4592571595?check_suite_focus=true#step:8:368 on Windows, and it does not seem to be reproduced locally. I wonder if it happens here 
```r
 rtools_home <- normalizePath(
      file.path(pkgbuild::rtools_path(), "..", ".."),
      winslash = "/",
      mustWork = TRUE
    )```
and if `pkgbuild::rtools_path()` detects two rtools, `v40` and `v42` for ucrt? Is it possible, @yutannihilation?

**Comment by Ilia-Kosenkov** [comment]
Oh yeah, that's `{pkgbuild}` fault https://github.com/r-lib/pkgbuild/releases/tag/v1.3.1

**Comment by Ilia-Kosenkov** [comment]
https://github.com/r-lib/pkgbuild/commit/2a9ce8d9c25c6dafb29ecb528247f49c10d8c59a#diff-5d9310c23b0c279cdd57b95238eb945cd45bac174c076244ad73cd4147deb626
https://github.com/r-lib/pkgbuild/blob/2a9ce8d9c25c6dafb29ecb528247f49c10d8c59a/R/rtools-metadata.R#L66-L69

File: R/source.R (hunk 6 above)
Comment (Ilia-Kosenkov) [reply R/source.R]: You were right, it seems to work fine.

**Comment by yutannihilation** [comment]
Oh, I forgot there's `ucrt64\bin`  bundled in Rtools. Your fix looks good to me.

Btw, we probably need to tweak this to handle the case of `RTOOLS42_HOME`.

https://github.com/extendr/rextendr/blob/9b2f49519b7b86a5b31f8ad20cd652566d43c498/R/source.R#L283

**Comment by Ilia-Kosenkov** [comment]
I think this will be needed for R 4.2.0+. I was hoping you can review and improve this when you investigate running extendr targeting `ucrt` :) I can help you with testing though

**Comment by yutannihilation** [comment]
Yeah, I'll take a look. I'm now using R-devel as my default environment so I'm almost ready for testing it! (except for uninstalling rtools40).

File: R/ui.R (hunk 7 above)
Comment (clauswilke) [reply R/ui.R:159]: I would suggest to add a few comments to the code explaining this reasoning. Whenever we have to do some weird trick to get something done, it's a good idea to write the reasoning down, as nobody will remember five years from now.

**Comment by malcolmbarrett** [comment]
I actually can't test this currently, which I think is directly related to #100. I've had trouble with my `PATH` and cargo with processx in the path 🤔

**Comment by malcolmbarrett** [comment]
I wonder if the `env` argument of `processx::run()` can somehow include the local `PATH` if it set up as in #99

**Comment by Ilia-Kosenkov** [comment]
I think I have addressed all the comments. Should I merge?

**Comment by clauswilke** [comment]
No concerns from my side.

**Comment by malcolmbarrett** [comment]
Once you merge this, people in my boat, e.g. who have #99 setup on Macs, may not be able to use the package (as I cannot with this PR). I don't necessarily think it's the responsibility of this PR to address it, but once merged, that issue and #100 become critical.

**Comment by clauswilke** [comment]
Actually, sorry for not connecting the dots earlier. I think @malcolmbarrett is making a good point. If this PR completely bricks the software for people with a reasonable setup (having a path set in `.Renviron` is totally reasonable) we have a problem.

**Comment by Ilia-Kosenkov** [comment]
Ok, I see. I suggest to switch this issue to draft and then investigate processx misbehavior. I have no Apple devices in my household, so it is difficult to debug this issue. I will try to find a MacOS VM to reproduce the problem and find a solution.

**Comment by yutannihilation** [comment]
I'd suggest merging this. As this is the development version, I think it's okay if the `HEAD` gets temporarily broken. As I commented on https://github.com/extendr/rextendr/issues/100#issuecomment-1000564058, I think the only choice is to add `PATH` wherever we use `cargo` (we need to fix the `Makevars` template as well). It probably takes some more changes, not all of which is related to this issue, so I want to separate the discussion, if this sounds okay to @malcolmbarrett.

**Comment by malcolmbarrett** [comment]
Yes, I think that's reasonable. This PR definitely escalates the issue, but I don't think it should necessarily be responsible for addressing it. Your solution looks compelling, @yutannihilation!

**Comment by yutannihilation** [comment]
Thanks for confirming!

**Comment by Ilia-Kosenkov** [comment]
Then I will merge it later today, thanks for the discussion.
